package com.app.flipprteachear.home.pojo.liveQuesPojo

import java.io.Serializable

data class Detail(
    val answer_details: List<AnswerDetail>,
    val chapter_id: String?=null,
    val chapter_name: String?=null,
    val cluster_name: String?=null,
    val content_creator_id: String?=null,
    val course_id: String?=null,
    val date_time: String?=null,
    var define_type: String?=null,
    val diagram_image: String?=null,
    val dimensions_id: String?=null,
    val exam_importance_id: String?=null,
    var flips_marks: List<FlipsMark>?=null,
    val image: String?=null ,
    val level_id: String?=null,
    val question: String?=null,
    val questions_all_types_id: String?=null,
    val segment_id: String?=null,
    val segment_name: String?=null,
    val solution_details: SolutionDetails?=null,
    val source_id: String?=null,
    val status: String?=null,
    val subject_id: Any?=null,
    val subtopic_id: String?=null,
    val subtopic_name: String?=null,
    val topic_image: String?=null,
    val topic_name: String?=null,
    val truefalse_answer_details: List<TruefalseAnswerDetail>?=null,
     val arrange_answer_details: List<ArrangeAnswerDetail>?=null,
    val type: String?=null,
   // var arrange_solution_details: List<ArrangeSolutionDetail?>? = null,
    //val truefalse_answer_details: List<TruefalseAnswerDetail>? = null,
    //val truefalseSolutionDetails: List<TruefalseSolutionDetail>? = null,
    val n_interpretation_answer_details: List<NInterpretationAnswerDetail>? = null,
    val n_visualization_ans_details: List<NVisualizationAnsDetail>? = null,
    val n_application_val_details: List<NApplicationValDetail>? = null,
    val n_application_details: List<NApplicationDetail>? = null,
    val numerical_solution_details: List<NumericalSolutionDetail>? = null,
    val descriptive_visualization_details: List<DescriptiveVisualizationDetail>? = null,
    val descriptive_answer_details: List<DescriptiveAnswerDetail>? = null,
    val descriptive_chapterkeyword_details: List<DescriptiveChapterkeywordDetail>? = null,
    val diagram_answer_details: List<DiagramAnswerDetail>? = null,
    val assertion_reasoning_details: List<AssertionReasoningDetail>? = null,
    val case_study_ques_details: List<CaseStudyQuesDetail>? = null,
     val fillup_answer_details: List<FillupAnswerDetail?>? = null,
      val case_study_details: List<CaseStudyDetail?>? = null

): Serializable